version: '3.4'

services:
  depth-quotes-producer:
    image: ${DOCKER_REGISTRY-}depth-quotes-producer
    build:
      context: .
      dockerfile: DepthQuotesProducer/Dockerfile
    environment:
      - Symbols__Symbol=ETHBTC
      - Nats__Url=nats:4222
    depends_on:
      - nats

  depth-quotes-consumer:
    image: ${DOCKER_REGISTRY-}depth-quotes-consumer
    build:
      context: .
      dockerfile: DepthQuotesConsumer/Dockerfile
    environment:
      - Nats__Url=nats:4222
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - depth-quotes-producer

  nats:
    image: nats:2.9.9
    ports:
      - "4222:4222"

  depth-client:
    image: ${DOCKER_REGISTRY-}depth-client
    build:
      context: .
      dockerfile: react-client/Dockerfile
    environment:
      REACT_APP_WS_URL: "ws://localhost:8080/ws/depthquotes"
    ports:
      - "3000:80"
    depends_on:
      - depth-quotes-consumer